### ISSUE TITLE
🐛 [BUG]: Typo-ish thing in readme

### ISSUE THREAD

**Issue by vkhobor** [nxtensions/nxtensions#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

In the readme, preview and development server sections show the same command.

Both are: nx dev my-app

### Expected behavior

Preview section should say i think: nx preview my-app

### Steps to reproduce

Open astro readme on github.

### Environment

Github on mobile. Npm package readme on mobile.

**Comment by leosvelperez** [comment]
hey @vkhobor! Thanks for reporting this! Would you be up for creating a PR with a fix?

**Comment by vkhobor** [comment]
Yea. I'll do it this weekend or monday sometime. Feel free to ping me if I forget.

**Comment by leosvelperez** [comment]
That's alright! I'm in the middle of updating Astro deps and will potentially update docs, so I might get to it sooner. Will close this if I do so.
