### ISSUE TITLE
✨ [Feature Request]: Support NX 15

### ISSUE THREAD

**Issue by digoburigo** [nxtensions/nxtensions#211]
### For which package(s) is the feature request for?

- [X] @nxtensions/astro
- [X] @nxtensions/tsconfig-paths-snowpack-plugin
- [ ] New package 🎉

### Background & Motivation

I want to able to use this in NX 15

### Possible solutions
Update dependencies?
### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by leosvelperez** [comment]
Fixed by #217.
