### ISSUE TITLE
🐛 [BUG]: On migrating to new version and upgrading Tailwind, utility classes cannot be detected

### ISSUE THREAD

**Issue by endymion1818** [nxtensions/nxtensions#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

I'm trying to upgrade my dependencies, I ran `nx migrate @nxtensions/astro@latest` then manually upgraded `tailwindcss` to 3.2.6, but now I'm getting the warning along with unstyled pages:

```
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
```

### Expected behavior

TailwindCSS continues to pick up the classes in my individual projects.

### Steps to reproduce

As described above, but also you can clone my repo https://github.com/endymion1818/personal-frontends-monorepo/pull/26 (`main` is broken too, so much for yolo deploys).

What I've tried so far:

1. Moving my tailwind.config.cjs to the root of the project 
2. Moving tailwind config to the root and adding the following

```
  content: [
    join(
      __dirname,
      './**/public/**/*.html',
      './**/src/**/*.{astro,md,js,jsx,svelte,ts,tsx,vue}',
      './libs/**/*.{astro,md,js,jsx,svelte,ts,tsx,vue}',
    ),
    ...createGlobPatternsForDependencies(__dirname)
  ],
```
Trying all sorts of other route patterns to no avail.

Does the tailwind.config.js file have to be in the root of the project now?

Thanks in advance for any and all assistance.

### Link to minimal reproducible example

https://github.com/endymion1818/personal-frontends-monorepo/pull/26

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : linux x64
   npm  : 8.19.3
   
   nx : 14.7.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.6
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.6
   @nrwl/js : Not Found
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nxtensions/astro: 3.3.0

**Comment by leosvelperez** [comment]
Thanks for reporting this!

You need to amend your TailwindCSS config, so the paths are correctly resolved from the project root:

```js
const { join } = require('path');

module.exports = {
  content: [
    join(__dirname, 'src/**/*.{astro,html,js,jsx,md,svelte,ts,tsx,vue}'),
    join(__dirname, '../../libs/**/*.{astro,html,js,jsx,md,svelte,ts,tsx,vue}'),
  ],
  ...
};
```

If you ever have libraries for a different application in the same workspace, it's better to use:

```js
const { createGlobPatternsForDependencies } = require('@nxtensions/astro/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{astro,html,js,jsx,md,svelte,ts,tsx,vue}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  ...
};
```

The `createGlobPatternsForDependencies` helper uses the project graph to collect the correct globs for the project's dependencies.

Please also note that you don't need the `postcss.config.cjs` file anymore to set up Tailwind CSS. You can safely remove it.

I'm closing this issue since it seems to be a wrong config. Please feel free to reopen it or leave a comment if you still have issues.

**Comment by endymion1818** [comment]
Fantastic, thank you!
