### ISSUE TITLE
✨ [Feature]: allow opting-out of component filename capitalization

### ISSUE THREAD

**Issue by louiss0** [nxtensions/nxtensions#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

The problem with `nxextensions/astro` is that is seems to capitalize the first letter of a component name that you are using. Astro just uses the page name as the route path and does not lowercase it. If I create a component called `Foo` the the word `/Foo` will be expected to be used in the name. This is not good. I wish I could go to the team about this but they are not going to fix this problem. 

### Expected behavior

I when I created a component in pages that it would not matter if the component was capitalized or not the path would be `/` plus the lowercase number but Astro does not work like that. 

### Steps to reproduce

You can test out the example by using the generate (ui) command. 

1. Activate the @nxextentions/astro component command in vs code
2. Go to the name of the component section 
3. Type a name 

What will happen is that you will see an auto-capitalization of the word 

### Link to minimal reproducible example

https://github.com/louiss0/frontmatter-cms-test

### Environment

   Node : 18.12.1
   OS   : win32 x64
   pnpm : 7.22.0

   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/vite              : 15.8.5
   @nrwl/nx-cloud          : 15.2.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @nxtensions/astro : 3.3.1

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `@nxtensions/astro:component` generator is for generating components, not pages. An Astro page is not a component, though it can use a similar syntax to that of components. I might provide a more comprehensive and dedicated page generator in the near future.

That said, I'll make the auto-capitalization optional with a default value of `true`. Flexibility doesn't hurt.
