### ISSUE TITLE
🐛 [BUG]: dev works, build fails -- it might be upstream -- discovery + workaround

### ISSUE THREAD

**Issue by firxworx** [nxtensions/nxtensions#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

Hello + huge thank-you to leosvelperez for putting `@nxtensions/astro` together and especially for figuring out the fiddly bits with Nx like the ESM compatibility and packaging up that knowledge for the community!

## Error summary

I added the latest version 16.0.0 and ran it through a dev + then build to make sure that works before going too far... and... the build will fail with error.

The easiest to replicate consistently happens at the "generating static routes" step: 

`renderers.mjs` will not be found as "imported from `index.astro.mjs`". In the example output below take note of the paths and how the supposed import is going back too many directories (and actually looking far outside the project directory for `renderers.mjs`!).

Note that no page in the source actually imports directly from `renderers`: this is related to the "under the hood" of Astro.

### Issue confirmed even with a "virgin" Astro app created by the generator

The example output includes a few lines regarding tailwind not finding a definition for `content` as this seems related to the issue. 

In fact, tailwind + postcss has a valid config that actually mirrors what I have in an older project that is working that was created with this same nx astro plugin.

In investigating this issue, I ran an experiment with a totally virgin `@nxtensions/astro` generated app with no added configurations to confirm the problem and rule out the involvement of other configuration + plugins such as tailwind.

> FWIW in case it helps anyone: specifying the path to `configFile` in the `tailwind()` plugin setup in `astro.config.mjs` helps the tailwind config get "found" (no more content missing error), however this leads to new error output, presumably also related to paths not lining up. Specifying the configPath (if its in the standard location alongside astro config) isn't necessary with the fix/workaround noted below.

## Direct replication using Astro CLI (+ fix/workaround)

I looked into the code for the build executor and confirmed it uses the Astro CLI. 

I was able to replicate the issue using the Astro CLI directly.

See the comments above the commands below:

```sh
# this will seemingly build but take careful note of the output vs. the error output below
pnpm astro build --config apps/op/astro-ui/astro.config.mjs

# this exactly replicates the error seen when using `pnpm nx build ...` !!!
pnpm astro build --root apps/op/astro-ui --config astro.config.mjs

# after ensuring outDir, srcDir, and publicDir are all explicitly specified the error goes away with the following
pnpm astro build --config apps/op/astro-ui/astro.config.mjs
```

The [docs for Astro CLI](https://docs.astro.build/en/reference/cli-reference/) helped a bit but they aren't the most clear on how `--root` actually behaves. The docs entries for `outDir`, `srcDir`, and `publicDir` helped.

It seems like `--root` totally borks the import paths + module resolution, and specifying only a config that then explicitly defines all required paths leads to a solution workaround.

I haven't used the Astro CLI directly before so if this is a new or unexpected behaviour then this points to the issue being upstream. I hope this helps anyone that encounters this issue and helps lead to an extension/fix for this extension :) 

## Example error output

````txt
pnpm nx build op-astro-ui

> nx run op-astro-ui:build

12:18:09 PM [content] No content directory found. Skipping type generation.
12:18:09 PM [build] output target: static
12:18:09 PM [build] Collecting build info...
12:18:09 PM [build] Completed in 3.70s.
12:18:09 PM [build] Building static entrypoints...

warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration
12:18:11 PM [build] Completed in 2.26s.

 building client
Completed in 1.08s.


 generating static routes
 error   Cannot find module '/home/username/projects/myproject/renderers.mjs' imported from /home/username/projects/m/yprojectdist/apps/op/src/pages/index.astro.mjs
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/username/projects/myproject/renderers.mjs' imported from /home/username/projects/myproject/dist/apps/op/src/pages/index.astro.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
1

 >  NX   Ran target build for project op-astro-ui (12s)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

```


### Expected behavior

Running `nx build <my-astro-app>` should work smoothly without error as it has done with previous versions of Astro and this plugin.

If `tailwind.config.cjs` is in the same directory as the Astro app in the nx monorepo under the apps folder and sitting alongside the `astro.config.mjs` file then there shouldn't be a need to specify the `configPath` argument to the `tailwind()` plugin.

### Steps to reproduce

See above.

### Link to minimal reproducible example

Easy to replicate on any nx with this extension.

### Environment

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : linux-x64
   pnpm   : 8.6.11

   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/esbuild        : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/express        : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/react          : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nxtensions/astro : 16.0.0
   ---------------------------------------

**Comment by firxworx** [comment]
Sharing more troubleshooting. I can get Astro working with tailwindcss when I do the following:

Downgrade `astro` to `2.6.5` which I know works from another project:

```sh
pnpm add astro@2.6.5
```

After changing the astro version you may have a stale cache issue with nx unless your next build you run with `--skip-nx-cache`:

```sh
pnpm nx build op-astro-ui --skip-nx-cache
```

In `astro.config.mjs` specify each of `outDir`, `srcDir`, and `publicDir` using full paths. The package `@nx/devkit` can help if you don't already have it installed in your project.

I also found that I needed to specify a `configFile` for the `tailwind` astro plugin or else I'd get a console warning about the `content[]` being empty.

```ts
import { workspaceRoot } from '@nx/devkit'

// ...

const APP_PATH = 'apps/path/to/your/app'
const _APP_ROOT = path.resolve(workspaceRoot, APP_PATH) // I found specifying `root` isn't required

const APP_SRC_ROOT = path.resolve(workspaceRoot, APP_PATH, 'src')
const APP_DIST_ROOT = path.resolve(workspaceRoot, 'dist', APP_PATH)

export default defineConfig({
  outDir: APP_DIST_ROOT,
  srcDir: APP_SRC_ROOT,
  publicDir: path.resolve(APP_PATH, 'public'),
 
  // ...

  tailwind({
      // path helps with astro cli borking paths
      // if not specified with the current config tailwind works but there's warning content path is empty
      configFile: path.resolve(workspaceRoot, APP_PATH, 'tailwind.config.js'),
    }),
// ...
```

In my `tailwind.config.js` I load a preset (and I also have my apps organized into subfolders so pay attention to the nesting for your case):

```
const srcContentPath = path.join(__dirname, 'src/**/!(*.stories|*.spec).{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}')
console.info(
  'using tailwind config: apps/op/astro-ui/tailwind.config.js',
)

/** @type {import('tailwindcss').Config} */
module.exports = {
  // you might not have a prefix
  presets: [require('../../../tailwind/tailwind-preset.js')],

  // this is important
  content: [srcContentPath, ...createGlobPatternsForDependencies(__dirname)],

  // you may or may not have these...
  // theme: { extend: {} },
  // plugins: [],
  // darkMode: ['class'],
}
```

Finally, no matter what I could do, this extension and tailwind keeps trying to find a postcss config at the root of the project (root of nx workspace). 

This is not correct behaviour for Nx workspaces. 

You can confirm correct behaviour, for example, with a React + Vite Bundler + Tailwind project created with the official Nx generators that they load the `postcss.config.js` from their respective app folders and not from the root. This was an important check for me to make sure that my workaround wouldn't bork my other projects in my Nx workspace (and perhaps you too!).

To workaround, I added `postcss.config.mjs` to the root of the project:

```js
import * as path from 'path'
import { fileURLToPath } from 'url'

// workaround with astro cli borking paths
// confirmed that astro+react w/ vite tailwind config reads the local postcss config in each apps' respective folder
// this workaround is specific to the astro app

// @todo remove this file when astro + nx sort themselves out (see links to issues in astro README)

// define cjs standbys for this mjs file 
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const opAstroUiTailwindConfig = path.join(__dirname, 'apps/op/astro-ui', 'tailwind.config.js')

// astro + tailwind is picking up this postcss config vs. the one in the app's root path
new Array(2).fill(undefined).forEach((_) => {
  console.warn('WARN postcss.config.mjs at project root (configured for op-astro-ui only)')
})

/** @type {import('postcss-load-config').Config} */
export default {
  plugins: {
    tailwindcss: {
      // if not specified the astro project will lose all styles
      config: opAstroUiTailwindConfig,
    },
    autoprefixer: {},
  },
}
```

ALL TOGETHER these interventions allow both `pnpm nx dev op-astro-ui` and `pnpm nx build op-astro-ui` to work with tailwind.

(Don't forget to skip nx cache when rebuilding after changing astro versions!)

This last one with the postcss config looks to be the exact issue that @jesusvallez just posted to https://github.com/nxtensions/nxtensions/issues/446

I think that bug can stand on its own and its sounds related specifically to `@nxtensions/astro` vs. a greater problem with the `astro` CLI. This plugin should behave like other Nx generators that support tailwind and always use the postcss config and tailwind config found within each project's respective app folder.

I hope this helps y'all :)

**Comment by leosvelperez** [comment]
@firxworx Thanks for reporting this and for the research!

This is an upstream issue, as you guessed. I provided some context on the issue you created in the Astro repo https://github.com/withastro/astro/issues/7934#issuecomment-1666480514. Hopefully, they address it soon.

Please note the issue starts to happen with Astro v2.9.7, so you could downgrade to v2.9.6 if it's not critical to have the latest version or you can use the workaround you proposed in https://github.com/nxtensions/nxtensions/issues/445#issuecomment-1664683087 in the meantime.

The Tailwind CSS issue is separate and I'll push a fix for it later. I added some context in the relevant issue https://github.com/nxtensions/nxtensions/issues/446.

**Comment by jesusvallez** [comment]
It seems that as of version 2.10.2 this is now fixed
https://github.com/withastro/astro/releases/tag/astro@2.10.2

**Comment by uptownhr** [comment]
@leosvelperez fyi this seems to have opened again after upgrading astro to 3.0
