### ISSUE TITLE
🐛 [BUG]: 

### ISSUE THREAD

**Issue by kjetilhp** [nxtensions/nxtensions#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What package does the issue affects?

@nxtensions/astro

### Describe the bug

❯ nx generate @nxtensions/astro:app astro-plain

>  NX  Generating @nxtensions/astro:application

✔ What frameworks and/or addons would you like to enable? · solid-js, svelte, vue, partytown, sitemap, tailwind

 >  NX   Cannot parse tools/scripts/patch-nx-cli.js: InvalidSymbol in JSON at 12:1

     10 |  * disabled (e.g. in CI environments).
     11 |  */
   > 12 | const { readFileSync, writeFileSync } = require('fs');
        | ^^^^^
     13 | 
     14 | try {
     15 |   const path = 'node_modules/nx/bin/nx.js';
   
   Pass --verbose to see the stacktrace.

### Expected behavior

not that...

### Steps to reproduce

create nx package based repo (not standard folder names for packages directory)

### Link to minimal reproducible example

N/A

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : darwin-arm64
   pnpm   : 8.6.12
   
   nx (global)        : 16.7.2
   nx                 : 16.7.2
   @nx/js             : 16.7.2
   @nx/jest           : 16.7.2
   @nx/linter         : 16.7.2
   @nx/workspace      : 16.7.2
   @nx/angular        : 16.7.2
   @nx/cypress        : 16.7.2
   @nx/esbuild        : 16.7.2
   @nx/eslint-plugin  : 16.7.2
   @nx/nest           : 16.7.2
   @nx/node           : 16.7.2
   @nrwl/nx-plugin    : 16.7.2
   @nx/storybook      : 16.7.2
   @nx/vite           : 16.7.2
   @nx/web            : 16.7.2
   @nx/webpack        : 16.7.2
   nx-cloud           : 16.4.0-beta.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @analogjs/content           : 0.2.0-rc.5
   @analogjs/router            : 0.2.0-rc.5
   @jscutlery/semver           : 3.1.0
   @ngrx/effects               : 16.2.0
   @ngrx/store                 : 16.2.0
   @ngrx/store-devtools        : 16.2.0
   @nguniversal/builders       : 16.2.0
   @nguniversal/express-engine : 16.2.0
   @nxtensions/astro           : 16.2.0
   @taiga-ui/cdk               : 3.41.1
   @taiga-ui/core              : 3.41.1
   ngfire                      : 0.0.52

```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can reproduce the issue with the information provided. Please provide a repo with a minimal reproduction so I can troubleshoot this.

As a side note, please keep in mind the plugin is tailored for [integrated workspaces](https://nx.dev/concepts/integrated-vs-package-based#integrated-repos), not for [package-based workspaces](https://nx.dev/concepts/integrated-vs-package-based#package-based-repos). As the Nx documentation states, in package-based repos, you use Nx primarily for speed and task scheduling. You want Nx to stay mostly out of your way and you set up everything on your own (aka, you don't use plugins).
