### ISSUE TITLE
✨ [Feature Request]: Astro 3.0 support

### ISSUE THREAD

**Issue by andersonba** [nxtensions/nxtensions#488]
### For which package(s) is the feature request for?

- [X] @nxtensions/astro
- [ ] @nxtensions/tsconfig-paths-snowpack-plugin
- [ ] New package 🎉

### Background & Motivation

With the release of [Astro 3.0](https://astro.build/blog/astro-3/), there have been significant improvements in performance and new features added to the framework.

However, the current version is not fully compatible. When attempting to run an app that leverages the new version, specifically, one of the most critical issues is that running the application with `nx serve` fails to start the development server as expected.

---

_I'm not sure if the type of issue I created is the correct one. I was unsure whether this was a bug or a feature, so please forgive me for that._

### Proposed Solution

Upgrade guide:

https://docs.astro.build/en/guides/upgrade-to/v3/

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by louiss0** [comment]
I need this too the server is not working and so is tailwind. 
Both broke here is the repo http://www.github.com/louiss0/dummy-with-astro3.

**Comment by M0nica** [comment]
The astro port in 3.x has also been updated to use 4321 instead of 3000 which I believe is breaking the https://github.com/netlify/cli's ability to detect the proper port for V3 Astro apps as it is always defaulting to waiting for port 3000.

**Comment by firxworx** [comment]
Noting here that #491 was closed in favour of #512 by its OP.

https://github.com/nxtensions/nxtensions/pull/491#issuecomment-1748846619

Refer to #512 for PR
